
/* Autogenerated file, do not edit! */

/* eslint-disable */

import { Noir, InputMap, CompiledCircuit, ForeignCallHandler } from "@noir-lang/noir_js"


export type u8 = string;
export type Field = string;

export type Action = {
  action_type: u8;
  actor_id: u8;
  target_x: u8;
  target_y: u8;
}


export type serialize_actions_0InputType = {
  actor_id: u8;
}

export type serialize_actions_0ReturnType = Field[];
export const serialize_actions_0_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8},"visibility":"private"}],"return_type":{"abi_type":{"kind":"array","length":1,"type":{"kind":"field"}},"visibility":"public"},"error_types":{}},"bytecode":"H4sIAAAAAAAA/6WOSQrDMAwArfbS52hzLN36FhP7/0/oEgWcBXLIgBgdhBhIC/Cdx7A/wz9eact69w4LTqpz4UZC3tmrZVStk5FRLnlmE2mmVrx6QSeVRj27dPxD4y+8B8FZF0eXRxdHl193QToCO498AP2MnIdQAQAA"};

export async function serialize_actions_0(actor_id: u8, foreignCallHandler?: ForeignCallHandler): Promise<Field[]> {
  const program = new Noir(serialize_actions_0_circuit);
  const args: InputMap = { actor_id };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as Field[];
}
export type serialize_actions_1InputType = {
  actor_id: u8;
  action: Action;
}

export type serialize_actions_1ReturnType = Field[];
export const serialize_actions_1_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8},"visibility":"private"},{"name":"action","type":{"kind":"struct","path":"skpla::action::Action","fields":[{"name":"action_type","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_x","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_y","type":{"kind":"integer","sign":"unsigned","width":8}}]},"visibility":"private"}],"return_type":{"abi_type":{"kind":"array","length":1,"type":{"kind":"field"}},"visibility":"public"},"error_types":{}},"bytecode":"H4sIAAAAAAAA/6WSbwrDIAzFZ23HjpMYrcm3XWWlev8jrNsiiJMV3IMQecjPPy/m8tFy1FXX5iir/aVb45mON3U82/Fm9WqVc+/aCVbvU3QJCSU72TiA99vKyBhi2B0TJfYcZZMIgp4S5iCU4S1sWFRYD1BWUBafs0x7r32cNX2/EUdZtvdfMMaaKxb8J1x+5Siao9Mc5TzHpZqTMmdW56j2271FT0jkDHvgAgAA"};

export async function serialize_actions_1(actor_id: u8, action: Action, foreignCallHandler?: ForeignCallHandler): Promise<Field[]> {
  const program = new Noir(serialize_actions_1_circuit);
  const args: InputMap = { actor_id, action };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as Field[];
}
export type serialize_actions_2InputType = {
  actor_id: u8;
  actions: Action[];
}

export type serialize_actions_2ReturnType = Field[];
export const serialize_actions_2_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8},"visibility":"private"},{"name":"actions","type":{"kind":"array","length":2,"type":{"kind":"struct","path":"skpla::action::Action","fields":[{"name":"action_type","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_x","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_y","type":{"kind":"integer","sign":"unsigned","width":8}}]}},"visibility":"private"}],"return_type":{"abi_type":{"kind":"array","length":1,"type":{"kind":"field"}},"visibility":"public"},"error_types":{}},"bytecode":"H4sIAAAAAAAA/6WTaQ6DIBCF3ZeeZoZFhn+9So14/yNUW0wJjrXSl0wgL/CF5U2evdUvdfPzfKnSj6u6yMsZr2C8kvEqxqsZr2G8lvE6X6G2e9z9KGFQyhnhUOIDhB1Jg1LjQEiojZ4ESelIkbGjNWBRSYeztnKGlzBiyR1Lexads/L4XFM6q9jfEVNZJfdekMaq+LeHFFZ98I92vs5qjjNBV1ntt3yZa6wuYMF/wv6X3Aufe3ue+z77aOvzNSuV79sm6MtwXbx30xOWZtIRcAQAAA=="};

export async function serialize_actions_2(actor_id: u8, actions: Action[], foreignCallHandler?: ForeignCallHandler): Promise<Field[]> {
  const program = new Noir(serialize_actions_2_circuit);
  const args: InputMap = { actor_id, actions };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as Field[];
}
export type serialize_actions_3InputType = {
  actor_id: u8;
  actions: Action[];
}

export type serialize_actions_3ReturnType = Field[];
export const serialize_actions_3_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8},"visibility":"private"},{"name":"actions","type":{"kind":"array","length":3,"type":{"kind":"struct","path":"skpla::action::Action","fields":[{"name":"action_type","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_x","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_y","type":{"kind":"integer","sign":"unsigned","width":8}}]}},"visibility":"private"}],"return_type":{"abi_type":{"kind":"array","length":1,"type":{"kind":"field"}},"visibility":"public"},"error_types":{}},"bytecode":"H4sIAAAAAAAA/6WUaQ6DIBBG6773LDMCAv96lRr1/keotJoaOi7QLyGYl/iiwzDB7ZNmXvflOZhXtOwmucUCgoUEiwgWEywhWEqwjGA5wQqClQSrCFYvbJu1Lo9lZ9BxPsp2RIZPaHWvBHDRdwoVCimGVjE2Kq6k7rUEjZyNOAnNJngHLRfbdalzV2B/1+DvCn//EX1dEVUv8HPFdO3Bx5XsnKOe3F3pfk8oV1d21F/SzZUf9iqfXFzFWd/z667y/A6Jq67qyn2Ea65644L/go3LnNDnc6K5fbPOWXO3zJ0wvWx6cJ2L5qxMjU1taus927XmBcjN6zsABgAA"};

export async function serialize_actions_3(actor_id: u8, actions: Action[], foreignCallHandler?: ForeignCallHandler): Promise<Field[]> {
  const program = new Noir(serialize_actions_3_circuit);
  const args: InputMap = { actor_id, actions };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as Field[];
}
export type serialize_actions_4InputType = {
  actor_id: u8;
  actions: Action[];
}

export type serialize_actions_4ReturnType = Field[];
export const serialize_actions_4_circuit: CompiledCircuit = {"abi":{"parameters":[{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8},"visibility":"private"},{"name":"actions","type":{"kind":"array","length":4,"type":{"kind":"struct","path":"skpla::action::Action","fields":[{"name":"action_type","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"actor_id","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_x","type":{"kind":"integer","sign":"unsigned","width":8}},{"name":"target_y","type":{"kind":"integer","sign":"unsigned","width":8}}]}},"visibility":"private"}],"return_type":{"abi_type":{"kind":"array","length":1,"type":{"kind":"field"}},"visibility":"public"},"error_types":{}},"bytecode":"H4sIAAAAAAAA/63VW26DMBBA0RLyIG/oSmawjcd/3UpdzP6XUKY1UkonYGhHQo7uxxEixmQv31P112v8nfVXHleeYtQyoW2ElgttK7Sd0PZCOwitENpRaCehnYV2EdpVaDeh3YVWxvY4VVzf4qqgUTrYOqDCd6idJwPa+IaQ0JBpa1IqkCbrvLPgUKuAnXGqg6/B7Keldbve2oytYHGtlf+26gDrrK1koYI11k620HXLrf0Tq78vWmodnlvO22VWMWWR7pZYx0mrvy+dbp3mLONNqnWetxqCNOuSYiFBinVNs9DYeeuWapH5mLPu6VZb22mrfLDgb4PV/1nAxnC+8gzfJj6L+Azhd5/f2eFbwnub9yTvJd4D/N/xM+dnVY6csT3MJ5W4yY5EBwAA"};

export async function serialize_actions_4(actor_id: u8, actions: Action[], foreignCallHandler?: ForeignCallHandler): Promise<Field[]> {
  const program = new Noir(serialize_actions_4_circuit);
  const args: InputMap = { actor_id, actions };
  const { returnValue } = await program.execute(args, foreignCallHandler);
  return returnValue as Field[];
}
